#-------------------------------
# General Site Settings

title: ヘラクレス
description: ヘラクレスの公式(非公式)ブログです。 # this means to ignore newlines until "baseurl:"
baseurl: "/rcj" # the subpath of your site, e.g. /blog
url: "https://rp-800.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name: ヘラクレスの中の人
author-avatar: icon.jpg


#-------------------------------
# Contact links
twitter: https://twitter.com/red_panda_RCJ # Add your Facebook handle
github: https://github.com/RP-800


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

timezone: Asia/Tokyo

#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
